# Generated by Django 6.0.6 on 2026-07-23 07:21

import apps.recruiters.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('industry', models.CharField(choices=[('software', 'Software'), ('information_technology', 'Information Technology'), ('fintech', 'FinTech'), ('healthcare', 'Healthcare'), ('education', 'Education'), ('ecommerce', 'E-Commerce'), ('telecom', 'Telecommunication'), ('manufacturing', 'Manufacturing'), ('banking', 'Banking'), ('automobile', 'Automobile'), ('media', 'Media'), ('real_estate', 'Real Estate'), ('logistics', 'Logistics'), ('consulting', 'Consulting'), ('other', 'Other')], default='software', max_length=50)),
                ('organization_type', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('government', 'Government'), ('startup', 'Startup'), ('non_profit', 'Non Profit')], default='private', max_length=30)),
                ('company_size', models.CharField(choices=[('1-10', '1 - 10 Employees'), ('11-50', '11 - 50 Employees'), ('51-200', '51 - 200 Employees'), ('201-500', '201 - 500 Employees'), ('501-1000', '501 - 1000 Employees'), ('1001-5000', '1001 - 5000 Employees'), ('5000+', '5000+ Employees')], default='1-10', max_length=20)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.recruiters.models.company_logo_upload_path)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.recruiters.models.company_cover_upload_path)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('linkedin', models.URLField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=150)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='recruiters/profile/')),
                ('is_primary', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiters', to='recruiters.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiters',
                'ordering': ['company', 'user'],
            },
        ),
    ]
