# Generated by Django 6.0.6 on 2026-07-08 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='phone',
        ),
    ]
