# Generated by Django 6.0.6 on 2026-07-10 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0008_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('portfolio', models.URLField(blank=True)),
                ('leetcode', models.URLField(blank=True)),
                ('hackerrank', models.URLField(blank=True)),
                ('codechef', models.URLField(blank=True)),
                ('codeforces', models.URLField(blank=True)),
                ('kaggle', models.URLField(blank=True)),
                ('stackoverflow', models.URLField(blank=True)),
                ('medium', models.URLField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='candidate.candidateprofile')),
            ],
        ),
    ]
